### ISSUE TITLE
Add info: NODE_ENV set by Vue.js CLI

### ISSUE THREAD

**Issue by djhuistra** [gtalarico/flask-vuejs-template#12]
So far I have been very happy with the template, but it took me a long while to figure out why you used 'NODE_ENV' in the Vue.js client. It seemed like a magical variable that didn't get set. 

I just figured out that the Vue.js CLI set's this variable to production when you run build. 

I figured I could save others the trouble of discovering this by suggesting you document this behaviour somewhere :)

Thanks for the great work on the template!

**Comment by gtalarico** [comment]
Hi! Thanks for the note. 
Happy to merge a PR if you want to do an edit on the Readme to include this.

**Comment by gtalarico** [comment]
Docs from Vue/webpack on `NODE_ENV` are here:
https://vuejs-templates.github.io/webpack/env.html
https://vuejs.org/v2/guide/deployment.html
