### ISSUE TITLE
Typescript?

### ISSUE THREAD

**Issue by ChaosCA** [gtalarico/flask-vuejs-template#14]
Vue 2.5+ has some improvements for Typescript. Would be really cool if you could showcase how that works with Vue

**Comment by gtalarico** [comment]
Hi! I haven't done any typescript myself. 
Feel free to fork and implement and would be happy to add a link on README

If you decide to go through with it, keep in mind I am in the process of refactoring the entire template on this branch:

https://github.com/gtalarico/flask-vuejs-template/tree/flatten-template-and-yarn
