### ISSUE TITLE
Incorrect line about Django

### ISSUE THREAD

**Issue by mtn** [gtalarico/flask-vuejs-template#15]
> #### Release
> The Procfile will run _Django migrations and then launch Django's_ app using gunicorn, as recommended by heroku.

I could be missing something, but I think these references to Django are probably mistakes. Thanks! 🎈

**Comment by gtalarico** [comment]
I borrowed a few things from my [django template](https://github.com/gtalarico/django-vue-template) in my last update and that slipped through.
Thanks!
