### ISSUE TITLE
How to turn on debug mode

### ISSUE THREAD

**Issue by soyaine** [gtalarico/flask-vuejs-template#17]
When I run `python run.py`, I got:
```
 * Serving Flask app "app" (lazy loading)
 * Environment: production
   WARNING: Do not use the development server in a production environment.
   Use a production WSGI server instead.
 * Debug mode: off
 * Running on http://127.0.0.1:5000/ (Press CTRL+C to quit)
```

I've tried to run `python run.py FLASK_CONFIG=development` but not work. Could you please explain where to config the env (debug mode) in README?

**Comment by mercuryZ** [comment]
On the Linux system, try
export FLASK_APP=run
on the Windows system, try
set FLASK_APP=run
P.S. flask always navigates the app.py and wsgi,py on its own.

**Comment by gtalarico** [comment]
Sorry guys I hadn't looked at this in a little while.
The correct answer is: make sure you have Flask 1.0+

Flask 1.0+ will automatically load `.flaskenv` file that is included and will be in development by default.

Set `FLASK_ENV` manually to `development` or `production` to override as needed.
`FLASK_APP` is also set in `.flaskenv` 
`FLASK_CONFIG

I am preparing a PR with updated docs on this, and updating the pipfile.lock to include Flask 1.0

**Comment by gtalarico** [comment]
Updated dependencies and doc string on `config.py`
upgrade flask to 1.0+ and you should be all set
