### ISSUE TITLE
Question: The purpose of Genome?

### ISSUE THREAD

**Issue by djhuistra** [gtalarico/flask-vuejs-template#2]
First of all, thanks for publishing this :) I really want to develop an app with this stack and this is a great starting point!

However. I am a bit confused by the repeated mentionings of "Genome".  

It is mentioned in the README of the Vue app (app/client/app/README.md) and also in two other places. The only thing I can find related to this is the Vue-Genome project (https://github.com/doximity/vue-genome) but you do not seem to import this. 

In addition, since you mention that comments are welcome, I have two suggestions:
- Maybe update the README of the Vue app with some more info.
- Maybe add a simple example of the Vue app actually retrieving some info from the Flask API?

**Comment by gtalarico** [comment]
Genome is a personal project that I am working on that I used as a template for this. All mentions can be removed.
Completely agree with the Api example, I will add that when I get a chance.

**Comment by djhuistra** [comment]
Thanks! That makes sense. I will make a pull request to remove the mentionings :)
