### ISSUE TITLE
Api static file

### ISSUE THREAD

**Issue by taraokelly** [gtalarico/flask-vuejs-template#5]
Hi, thank you very much for posting this template! I'm having an issue referencing static files in the api template. I created a static folder in **_/app/api/_**. Then I tried to specify the static folder and static folder url in  **_/app/api/__init__.py_**.

However, nothing seemed to work. Would you know how to solve this is issue?

**Comment by gtalarico** [comment]
I am sorry I don't think I understand your question. Could you post code samples?

**Comment by taraokelly** [comment]
I couldn't load static files using **url_for()** in the api template. I solved the issue, thanks for your time.
